repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: detect-private-key
    - id: detect-aws-credentials
      args:
      - --allow-missing-credentials
    - id: check-case-conflict
    - id: check-json
    - id: check-symlinks
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: trailing-whitespace
      args:
      - --markdown-linebreak-ext=.md

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v1.3.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: [] # optional: list of Conventional Commits types to allow

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.15.0
  hooks:
    - id: eslint
      files: \.[jt]sx?$|\.vue$
      types: ["file"]
      additional_dependencies:
        - eslint@4.15.0
        - eslint-config-google@0.7.1
        - eslint-loader@1.6.1
        - eslint-plugin-react@6.10.3
        - babel-eslint@6.1.2
