name: Deploy Preview to Firebase Hosting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  

jobs:
  preview_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.0.0
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "{{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "{{ secrets.FIREBASE_SERVICE_ACCOUNT_JFGI_SITE }}"
          projectId: "{{ secrets.FIREBASE_PROJECT_ID }}"
          expires: 7d
