name: Deploy Release to Firebase Hosting
on:
  - release

jobs:
  release_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "{{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "{{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "{{ secrets.FIREBASE_PROJECT_ID }}"
          channelId: live